### ISSUE TITLE
Topic

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/Hailing_Frequencies#1]
Let's all pick two topics, probably ideas from or modified from suggestions on the Score page. Then we can come up with a top one or two.

**Comment by ericaddison** [comment]
My two choices:

Dynamic Risk game
http://score-contest.org/2016/projects/drisk.php

ChannelX
http://score-contest.org/2018/projects/channelx.php

**Comment by psigourney** [comment]
Will post something up tomorrow.

**Comment by ericaddison** [comment]
Any thoughts on this, guys?

**Comment by psigourney** [comment]
I think the chat room service thing would be good.
User joins, sees list of existing chat rooms available to join or create new room.  Join room, live chat with others in the same room, etc.

**Comment by ericaddison** [comment]
I think a chatroom app would be fun, too.

I definitely think we should get approval from Christine about it, because Audrey and her team sent in their idea for approval, which was a recipe->shopping list app, and they got a little bit of push back about what will differentiate their app, and how does it compare to other similar apps on the market...

**Comment by ericaddison** [comment]
I pinged Christine with a quick email asking about final project scope. I mentioned our idea is for some kind of chatroom app, and also mentioned that we had considered the "ChannelX" app (which is also kind of a chatroom).

**Comment by ericaddison** [comment]
I'm starting to like the idea of the ChannelX project more... It would be fun I think. I'm already looking at text message APIs ($$$, so using text would have to be a premium feature :) )

**Comment by mspagon** [comment]
I really like the DRISK game but I think the scope is too large.  Simply implementing risk is hard enough let alone allowing uploading of maps/random generation of maps. And it seems like it would be pretty javascript intensive.

I'm down to talk more about ChannelX today.  I need help envisioning how it would work.

**Comment by ericaddison** [comment]
I agree the DRISK would be tons of fun, but probably too much custom UI stuff for us to take on in a month!

**Comment by ericaddison** [comment]
I started jotting down some notes in an old google doc we had about the final project:
https://drive.google.com/open?id=1i58IknNIB4_qEExWt48MdbjJujgEWdspdckrYfbGNI0

**Comment by ericaddison** [comment]
And here I started working on some wireframes
https://ninjamock.com/Designer/Workplace/21014847/WebChatroom

Also invited you guys to that project on NinjaMock

**Comment by ericaddison** [comment]
I know we've essentially settled on a topic, but in case we want an alternative, I was thinking of an app (web app mainly, maybe a simplified mobile version) that is kind of like a daily work log. 

Do you take notes on stuff while you are working on programming? Or any other project? Do you take notes so you can remember what you were doing after a weekend is over? I'm thinking of an app that is some kind of combination of WorkFlowy and MS OneNote, where you can keep notes or logs about a project. There would be one central daily log that you could write to directly, but also you could keep notes about different components separately (maybe specific issues, bugs, files, classes, ideas, etc ... maybe have customizeable categories?), but entries on those things would all be entered into the master log, so you could always get a good summary of what you worked on in any given day. Also the use of tags, search, and filtering could be cool to maybe quickly get a history of what you've done for some specific topic (say, search for log entries like "segfault"). 

Could be pretty simple technically, we would just have to put in good thoughts about the design and how self-connected we want it to be. Maybe have ability to drag and drop images to add to the log, add PDFs to the log, link to github, or print out the log to PDF. Also could invite others to view or edit the logs, maybe like a "team" mode.

Just another idea, in case either of you aren't feeling the channelX project :)

App name: WorkLoggy

Also sounds like this might not be a saturated area ... here is a blog post from thie Juanuary talking about how you could use _other_ apps to kind of function as a work log
http://alycevayleauthor.com/2017/01/20/apps-to-create-a-daily-work-log-how-to-keep-a-daily-activity-diary/
