### ISSUE TITLE
Messages Data Model

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/Hailing_Frequencies#13]
Hi @psigourney!

Soooo, on the miniproject you sounded convinced that we should use the `repeated` property for our model properties instead of extra models like `StreamSubscriber`. Now it looks like you made a `ConvMessages` class as well that will serve a similar purpose. I still like this idea, but curious if you had some additional insight about it this time.
Thanks!

**Comment by psigourney** [comment]
Actually... thinking about it now.... Conversations could have a list of Messages keys, then the Message records would store the details.

**Comment by ericaddison** [comment]
Ah ok. And if I remember right, there is still a pretty simple query to retrieve all the messages associated with a user ... is that right?

**Comment by ericaddison** [comment]
Or I guess in that case you could still just query for all Messages with a given owner...

**Comment by psigourney** [comment]
Yeah, it would be something like *Messages.query('userId' ==
someUserIdValue).fetch()*

(or something like that)

**Comment by ericaddison** [comment]
Cool. I like that.
