### ISSUE TITLE
Anyone else having issue with current master?

### ISSUE THREAD

**Issue by mspagon** [ericaddison/Hailing_Frequencies#16]
JUST fyi

Having some issues running dev_appserver.py . on the current merge.

I didn't try all the various commit logs but it works for 

![image](https://user-images.githubusercontent.com/5027451/32718799-d857528a-c823-11e7-8075-ad270939088a.png)

![image](https://user-images.githubusercontent.com/5027451/32718666-5f70f024-c823-11e7-90c8-ee68ba2150fa.png)

**Comment by ericaddison** [comment]
Different issue, same result. @psigourney , I crash saying "No module named google.auth"

How did you get that to work?

**Comment by psigourney** [comment]
From the screenshots, it looks like it could have been the inclusion of Flask stuff to AjaxStuff.py.  After the call last night, I just deleted AjaxStuff altogether and redirected the ajax calls to user_authentication.  See if the latest push works.

**Comment by psigourney** [comment]
I was able to get google.auth to work by going into PyCharm File > Settings > Project Interpreter and removing google-auth from the list.  I had added it to the /lib directory (lib//google/auth) and it seems having PyCharm thinking it had installed a copy was causing issues.

**Comment by ericaddison** [comment]
I just had the same problem again ... modified `appengine_config.py` to be more explicit about library location. Worked for me, hopefully doesn't break you!

**Comment by ericaddison** [comment]
Closing this if @psigourney did not have trouble...
