### ISSUE TITLE
Firebase Structure

### ISSUE THREAD

**Issue by psigourney** [ericaddison/Hailing_Frequencies#28]
I think we need to have a discussion about how data will be structured in Firebase.

https://console.firebase.google.com/project/hailing-frequencies-2017/database/hailing-frequencies-2017/data

There are both messages and Conversation sections... are these compatible with each other (containing different data), or are the different methods writing data differently?

**Comment by ericaddison** [comment]
Looks like the Messages tree does something like messages->conv ID->array of messages. Is that right? I like how that looks... Should we include a date field with the messages?

**Comment by mspagon** [comment]
I'm guessing a lot of the data on there is jumbled and old.  I was experimenting and you were doing different things.  Don't go off by what's on there we should wipe it.

How much detail we want to store with the messages on Firebase is better left up to someone who understands how to architect system (not me).  Here is what I have, basically **Conversation** should only store the last message posted to the conversation (used for when you want to preview the last message) and NOT all of the messages.  Basically just follow this [thread](https://firebase.google.com/docs/database/rest/structure-data) which discusses how to store conversations, users, and messages.

**Android uses Java classes when writing to Firebase, much like Python does for NDB.  We need to establish a model on gitHub that we all follow, whether its just a .readme or something**

```Java
public class Conversation {
    private String title;  // or however we identify Conversations (ID #)
    private User admin;  //Technically can look up using NDB and don't need this here?
    private Message lastMessage;
}

public class ConvMessages {
    private Conversation conversation;
    private List<Message> messageList;
}

public class ConvUsers {
    private String title;
    private User Admin;  //Technically can look up using NDB and don't need this here?
    private List<User> userList;
}

public class Message {
    private String alias;  //could be of type User??
    private String photoUrl;
    private String text;
    private Timestamp time;
}

//What goes in User?
public class User {
    private String email;
    private String alias;
   //Any extra variables here?
}
```

**Comment by mspagon** [comment]
The Android Java model will be declared here (but I don't think I need it anymore since Android will not be writing to Firebase because we plan on changing to REST calls).
https://github.com/mspagon/Hailing_Frequencies_Android/tree/master/app/src/main/java/com/apt/hailingfrequencies/models

**Comment by ericaddison** [comment]
@mspagon 
You should only need to create Java classes that represent our database objects for convenience of parsing the JSON that gets returned from the API. Basically the job of Android (or web) is to request or submit JSON information from our REST API (i.e. our AppEngine server) and update the UI accordingly, so the use of replicating the data models as Java classes would be to make the received JSON easier to work with. To decide what fields should be in the Java classes, I would look at what gets returned when you receive a JSON from the API. For example, when you retrieve a full `Conversation`, you get a JSON populated from [this function](https://github.com/ericaddison/Hailing_Frequencies/blob/master/source/models/Conversations.py#L55), so the Java corresponding to that might look like:
```java
public class Conversation{
  long id;
  String name;
  Timestamp createDate;
  Timestamp destroyDate;
  String[] aliases;
  String idPolicy;
  boolean viewAfterExpire;
  boolean revealOwner;
  String restrictComms;
}
```
And then (hopefully), GSON would be able to automatically populate those fields if you feed it a JSON from our API...

Like you noticed, you don't have to write to Firebase directly, just POST to our API (see the [api unit tests](https://github.com/ericaddison/Hailing_Frequencies/blob/master/test/api/live_api_test.py) for lots of examples of how to for the URLs.)
