### ISSUE TITLE
Week of 11/5

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/Hailing_Frequencies#6]
@psigourney @mspagon
Hey guys,

Mike, Patrick and I talked at the end of class about a better way to approach the project for timeline and milestones. I made a new timeline here:
https://docs.google.com/spreadsheets/d/1_USlIN1TR2E-l4ZHXYZ7DVFxl12J0hhvotoq0HBmmVM/edit#gid=0

Basically, we should be more parallel. For the first "phase", lets split the work like this:

Patrick: Data model (python classes, NDB schema, etc)
Eric: Anticipated Web API endpoints (management stuff like: get all conversations, join a conversation, and actual use stuff like post new message, edit message, etc)
Mike: Admin/Test dashboard (list users, rebuild database, test functionality, etc)
Obviously we will need to be communitcating during this process :)

The next steps, in a week and a half or so, will be:

Android front end
Web front end
Comm APIs
We can talk about who does which of these steps later.

This way we can be making good progress on multiple fronts in parallel, and stay out of each other's way to some extent (working on different files), but also be evolving the API/data model at the same timeso they build off each other. The admin/test dashboard should exercise the functions written for both the model and the API, so we can also get a good sense of how our components work and what we will need. Then, when it comes to making the front ends, we just need to make pages/activities and connect to the different API services we've created (and tested).

Sound OK???

**Comment by mspagon** [comment]
Sounds great!

**Comment by psigourney** [comment]
Yup.  Still need to look into the Firebase DB thing... whether to use it or NDB to store the conversation messages, the application data, both, or neither.

**Comment by ericaddison** [comment]
For now I would suggest we just move ahead with NDB as the primary DB (including for message history), and only regard Firebase as a means of real time interaction between apps and server... I say this because I think we plan to store some things in NDB, so kind of keeping only one DB solution would be good, I think, and really just think of Firebase as a communication medium (and authentication!).

My two cents :)

**Comment by ericaddison** [comment]
Hey guys, 
I have plans tomorrow night. Can we move our phone call to either the early afternoon or to Sunday? Thanks!

**Comment by mspagon** [comment]
Sunday would work best for me, but if necessary I can make anytime Saturday
work.

Thanks.
Michael

**Comment by psigourney** [comment]
Sunday is fine.

**Comment by ericaddison** [comment]
Fine with me! Still 8:30?
