### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/Hailing_Frequencies#8]
@psigourney 
I see you added some FireBase stuff to the project. Were you thinking about using FireBase for user authentication? That sounds like it might be an easy, good solution...

https://firebase.google.com/docs/auth/

**Comment by psigourney** [comment]
Looks like Firebase works through JavaScript?  Not sure if there is any benefit to it instead of using the Google authentication like we did for the mini-project? Unless it's so that a user can log in without using Google or some other 3rd party site?

**Comment by ericaddison** [comment]
Here's what I understand at the moment...
- Authentication starts with a client requesting to login, so from Javascript or Android
- Firebase Auth (or Auth0 as an alternative) provide convenient libraries (in Java and JavaScript) to authenticate (i.e. login) and I think receive an authentication token.
- The client sends that token to our API server when it makes a request (like post message, get user conversations, etc)
- Our client then authenticates that token via the right authentication server (Google, Facebook, GitHub, etc)
- The authentication server responds to our server with actual user details (or something like that)

Firebase (and Auth0 as an alternative) both provide client-side libraries that sound very easy to allow logging in through google, or facebook, or email/password, or whatever (like the Google login link we used before, but on steroids). 

So I do think this will be a better way to manage authentication. The Miniproject phase2 was super easy to do with only the web app and only with Google sign in, but even just doing the Google signin through Android was a bit of a pain. I think this will help pass that complexity to someone else :)

**Comment by ericaddison** [comment]
For example, here is how to add Auth0 to a JavaScript app:
https://auth0.com/docs/quickstart/spa/vanillajs

And here is the example firebaseUI project:
https://github.com/firebase/firebaseui-web
and demo:
https://fir-ui-demo-84a6c.firebaseapp.com/

**Comment by psigourney** [comment]
Got it.  Working on it now...

edit: if that's okay with everyone.  I didn't do much with auth in the first part, so I'd like to do it here to get familiar with it.

**Comment by ericaddison** [comment]
@psigourney 
Hey Patrick,
I didn't see your note about auth until just now. Looks like you are working on the auth through firebase, which is great. I also want to get more familiar with auth :) How about we both give it a try ... you work on FirebaseUI and I'll try for Auth0.

Either way, I'm guessing that in the end we will need to be passing an access token to the API server when we make API calls, so I'm going to write the API part with methods that assume such. I can't push until after work, but I'm writing a file in the `framework` package with methods like:
```python
user_authentication(access_token)
get_user_from_token(access_token)
verify_token(access_token)
get_user_from_token_auth0(access_token)
verify_token_auth0(access_token)
```
So if you want to write some methods like `get_user_from_token_firebase(token)` and `verify_token_firebase(access_token)`, when we can drop those into the API authentication, too.

Just to say it again, because the more times I repeat myself the better I might eventually understand ... I think we will both implement some kind of front-end piece that prompts the user to log in, after which maybe the front-end receives a token, or maybe gets redirected to another page with the token. After that, we need to save that token I think (or maybe just call back to the auth provider to get it again???) and send the token along with any API requests, so our API backend can authenticate users before allowing any calls to be completed.

Does that sound like your understanding at all???

**Comment by psigourney** [comment]
Are you able to `import google-auth`?

I can see it as a module installed by pip, but when I try to use it, I get an ImportError: `No module named google.auth`

For the FirebaseUI authentication, google-auth is used to validate the user tokens.

edit: so it's because the "google" that the appengine sees is in the google-cloud-sdk directory.
But the modules are all installed in the usr/local/lib/python2.7 directory.

edit2:  Tried this
`~/google-cloud-sdk/platform/google_appengine$ sudo -H pip install -t lib/ google-auth`

So the -t lib/ forces the installation to 
`~/google-cloud-sdk/platform/google_appengine/lib`

Then specify the directory:

`from google.appengine.ext import vendor
vendor.add('lib')`

But it still isn't finding it.

**Comment by psigourney** [comment]
ARGH.  FINALLY.  Literally ALL DAY spent trying to get google.auth imported.   And of course, I was doing it completely wrong.  (removing google-auth from the PyCharm Settings seemed to fix a lot of the problems)

**Comment by ericaddison** [comment]
Good work! That stuff is super frustrating!

**Comment by psigourney** [comment]
Firebase user auth is working.  I added a `token` field to the Users model which will make it easier to match the auth_token to a local User account.

Next step I think will be to tie-in the login page to create a new local user account in Users.

**Comment by ericaddison** [comment]
Cool that auth is working!

I'm not sure if storing the token to match against is a good idea. It's my understanding that these tokens can change as they expire. I think verifying the token and then extracting user info from it (e.g. email that we can use to look up the local account) is the right way to go.

**Comment by ericaddison** [comment]
@psigourney 
Oh also, I think we should use the API call POST to `/users/` to create a new user. By sending along the id token with the request, the `post_hook()` method [here](https://github.com/ericaddison/Hailing_Frequencies/blob/master/source/api/Users.py#L67) should be able to add the new user to the database.

Sooo... Maybe an option would be for your [get_user_from_token()](https://github.com/ericaddison/Hailing_Frequencies/blob/master/source/framework/user_authentication.py#L135) function (or any of those types of functions) to:
- retrieve user info from Firebase via the `id_token`
- try to look up current `user` using email
- if found, return that `user`
- if not, create a new temporary `user` object and return that

I think we should add a field to the `Users` model called `verified` or something, so we could think about adding in an email or phone verification step... The temporary `user` object created by a new token login would then be marked with `verified=False`, and only after some sort of verification does it get marked `True`.

**Comment by ericaddison** [comment]
@psigourney 
Nice work on the lastest push! I see the user info popping up from the token! Way cool!

**Comment by psigourney** [comment]
Still running into some problems getting user data into the Manage page.
When you click the clickable button it works fine (except the result is a
400 error), but trying to get it to trigger automatically (on page load or
after  FirebaseHeader.initApp().done) results in the function running too
soon and the user token hasn't been populated yet.

Looking into maybe including a callback with FirebaseHeader.initApp() so we
don't try to get the local user data until after initApp() gets its results.

**Comment by ericaddison** [comment]
Firebase working well. Good verification and lookup from tokens.
